ALTER TABLE badge CHANGE rarete rarete ENUM('COMMUN','RARE','EPIQUE','LEGENDAIRE') DEFAULT 'COMMUN';
ALTER TABLE comments DROP FOREIGN KEY `FK_5F9E962AA76ED395`;
ALTER TABLE comments DROP FOREIGN KEY `FK_5F9E962AE2904019`;
DROP INDEX thread_id ON comments;
CREATE INDEX IDX_5F9E962AE2904019 ON comments (thread_id);
DROP INDEX user_id ON comments;
CREATE INDEX IDX_5F9E962AA76ED395 ON comments (user_id);
ALTER TABLE comments ADD CONSTRAINT `FK_5F9E962AA76ED395` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT `FK_5F9E962AE2904019` FOREIGN KEY (thread_id) REFERENCES threads (id) ON DELETE CASCADE;
DROP INDEX idx_actif ON cours;
DROP INDEX idx_categorie ON cours;
DROP INDEX idx_niveau ON cours;
ALTER TABLE cours ADD document_path VARCHAR(500) DEFAULT NULL, ADD video_url VARCHAR(500) DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE categorie categorie VARCHAR(100) NOT NULL, CHANGE niveau_difficulte niveau_difficulte ENUM('DEBUTANT','INTERMEDIAIRE','AVANCE','EXPERT') NOT NULL DEFAULT 'DEBUTANT', CHANGE points_xp points_xp INT NOT NULL, CHANGE duree_estimee duree_estimee INT DEFAULT NULL, CHANGE certification certification TINYINT NOT NULL, CHANGE actif actif TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
ALTER TABLE donnees_business DROP INDEX projet_id, ADD UNIQUE INDEX UNIQ_E8382063C18272 (projet_id);
ALTER TABLE donnees_business CHANGE taille_marche taille_marche VARCHAR(255) DEFAULT NULL, CHANGE modele_revenu modele_revenu VARCHAR(255) DEFAULT NULL, CHANGE projet_id projet_id INT NOT NULL;
ALTER TABLE donnees_business ADD CONSTRAINT FK_E8382063C18272 FOREIGN KEY (projet_id) REFERENCES projet (id) ON DELETE CASCADE;
ALTER TABLE events DROP FOREIGN KEY `events_ibfk_1`;
ALTER TABLE events DROP FOREIGN KEY `events_ibfk_1`;
ALTER TABLE events CHANGE description description LONGTEXT DEFAULT NULL, CHANGE capacity capacity INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE events ADD CONSTRAINT FK_5387574ADE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX created_by ON events;
CREATE INDEX IDX_5387574ADE12AB56 ON events (created_by);
ALTER TABLE events ADD CONSTRAINT `events_ibfk_1` FOREIGN KEY (created_by) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE event_participants DROP FOREIGN KEY `event_participants_ibfk_1`;
ALTER TABLE event_participants DROP FOREIGN KEY `event_participants_ibfk_2`;
ALTER TABLE event_participants DROP FOREIGN KEY `event_participants_ibfk_1`;
ALTER TABLE event_participants DROP FOREIGN KEY `event_participants_ibfk_2`;
ALTER TABLE event_participants ADD CONSTRAINT FK_9C7A7A6171F7E88B FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE event_participants ADD CONSTRAINT FK_9C7A7A61A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX user_id ON event_participants;
CREATE INDEX IDX_9C7A7A61A76ED395 ON event_participants (user_id);
DROP INDEX event_id ON event_participants;
CREATE UNIQUE INDEX unique_participation ON event_participants (event_id, user_id);
ALTER TABLE event_participants ADD CONSTRAINT `event_participants_ibfk_1` FOREIGN KEY (event_id) REFERENCES events (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE event_participants ADD CONSTRAINT `event_participants_ibfk_2` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE groups DROP FOREIGN KEY `groups_ibfk_1`;
ALTER TABLE groups DROP FOREIGN KEY `groups_ibfk_1`;
ALTER TABLE groups CHANGE description description LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE is_private is_private TINYINT NOT NULL;
ALTER TABLE groups ADD CONSTRAINT FK_F06D39706D1BCE6F FOREIGN KEY (group_admin_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX group_admin_id ON groups;
CREATE INDEX IDX_F06D39706D1BCE6F ON groups (group_admin_id);
ALTER TABLE groups ADD CONSTRAINT `groups_ibfk_1` FOREIGN KEY (group_admin_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE group_members DROP FOREIGN KEY `group_members_ibfk_1`;
ALTER TABLE group_members DROP FOREIGN KEY `group_members_ibfk_2`;
ALTER TABLE group_members DROP FOREIGN KEY `group_members_ibfk_1`;
ALTER TABLE group_members DROP FOREIGN KEY `group_members_ibfk_2`;
ALTER TABLE group_members CHANGE joined_at joined_at DATETIME NOT NULL;
ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3FE54D947 FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE;
ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX user_id ON group_members;
CREATE INDEX IDX_C3A086F3A76ED395 ON group_members (user_id);
DROP INDEX group_id ON group_members;
CREATE UNIQUE INDEX unique_group_member ON group_members (group_id, user_id);
ALTER TABLE group_members ADD CONSTRAINT `group_members_ibfk_1` FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE group_members ADD CONSTRAINT `group_members_ibfk_2` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_investor`;
ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_opportunity`;
DROP INDEX idx_offer_status ON investment_offer;
ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_investor`;
ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_opportunity`;
ALTER TABLE investment_offer ADD paid TINYINT NOT NULL, ADD payment_intent_id VARCHAR(255) DEFAULT NULL, ADD paid_at DATETIME DEFAULT NULL, CHANGE status status ENUM('PENDING','ACCEPTED','REJECTED') DEFAULT 'PENDING', CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
ALTER TABLE investment_offer ADD CONSTRAINT FK_4615B1CA9AE528DA FOREIGN KEY (investor_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE investment_offer ADD CONSTRAINT FK_4615B1CA9A34590F FOREIGN KEY (opportunity_id) REFERENCES investment_opportunity (id) ON DELETE CASCADE;
DROP INDEX idx_offer_investor ON investment_offer;
CREATE INDEX IDX_4615B1CA9AE528DA ON investment_offer (investor_id);
DROP INDEX idx_offer_opportunity ON investment_offer;
CREATE INDEX IDX_4615B1CA9A34590F ON investment_offer (opportunity_id);
ALTER TABLE investment_offer ADD CONSTRAINT `fk_offer_investor` FOREIGN KEY (investor_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE investment_offer ADD CONSTRAINT `fk_offer_opportunity` FOREIGN KEY (opportunity_id) REFERENCES investment_opportunity (id) ON UPDATE CASCADE ON DELETE CASCADE;
DROP INDEX idx_opportunity_status ON investment_opportunity;
DROP INDEX idx_opportunity_deadline ON investment_opportunity;
ALTER TABLE investment_opportunity ADD risk_score DOUBLE PRECISION DEFAULT NULL, ADD risk_label VARCHAR(50) DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE status status ENUM('OPEN','CLOSED','FUNDED') DEFAULT 'OPEN', CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
ALTER TABLE investment_opportunity ADD CONSTRAINT FK_498180B166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id) ON DELETE CASCADE;
DROP INDEX idx_opportunity_project ON investment_opportunity;
CREATE INDEX IDX_498180B166D1F9C ON investment_opportunity (project_id);
ALTER TABLE mentor_availability DROP FOREIGN KEY `fk_availability_mentor`;
ALTER TABLE mentor_availability CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX fk_availability_mentor ON mentor_availability;
CREATE INDEX IDX_CB274DDFDB403044 ON mentor_availability (mentor_id);
ALTER TABLE mentor_availability ADD CONSTRAINT `fk_availability_mentor` FOREIGN KEY (mentor_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE mentorship_request DROP FOREIGN KEY `fk_request_entrepreneur`;
ALTER TABLE mentorship_request DROP FOREIGN KEY `fk_request_mentor`;
ALTER TABLE mentorship_request DROP FOREIGN KEY `fk_request_project`;
ALTER TABLE mentorship_request DROP FOREIGN KEY `fk_request_entrepreneur`;
ALTER TABLE mentorship_request DROP FOREIGN KEY `fk_request_mentor`;
ALTER TABLE mentorship_request DROP FOREIGN KEY `fk_request_project`;
ALTER TABLE mentorship_request CHANGE entrepreneur_id entrepreneur_id INT DEFAULT NULL, CHANGE mentor_id mentor_id INT DEFAULT NULL, CHANGE time time VARCHAR(50) DEFAULT NULL, CHANGE motivation motivation LONGTEXT DEFAULT NULL, CHANGE goals goals LONGTEXT DEFAULT NULL, CHANGE match_score match_score DOUBLE PRECISION DEFAULT NULL, CHANGE auto_approved auto_approved TINYINT NOT NULL, CHANGE status status VARCHAR(50) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1A283063EA FOREIGN KEY (entrepreneur_id) REFERENCES user (id);
ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1ADB403044 FOREIGN KEY (mentor_id) REFERENCES user (id);
ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1A166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id);
DROP INDEX fk_request_entrepreneur ON mentorship_request;
CREATE INDEX IDX_2F5D3C1A283063EA ON mentorship_request (entrepreneur_id);
DROP INDEX fk_request_mentor ON mentorship_request;
CREATE INDEX IDX_2F5D3C1ADB403044 ON mentorship_request (mentor_id);
DROP INDEX fk_request_project ON mentorship_request;
CREATE INDEX IDX_2F5D3C1A166D1F9C ON mentorship_request (project_id);
ALTER TABLE mentorship_request ADD CONSTRAINT `fk_request_entrepreneur` FOREIGN KEY (entrepreneur_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE mentorship_request ADD CONSTRAINT `fk_request_mentor` FOREIGN KEY (mentor_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE mentorship_request ADD CONSTRAINT `fk_request_project` FOREIGN KEY (project_id) REFERENCES projet (id) ON DELETE SET NULL;
ALTER TABLE mentorship_session DROP FOREIGN KEY `fk_session_request`;
ALTER TABLE mentorship_session CHANGE mentorship_request_id mentorship_request_id INT DEFAULT NULL, CHANGE scheduled_at scheduled_at DATETIME DEFAULT NULL, CHANGE duration_minutes duration_minutes INT DEFAULT NULL, CHANGE status status VARCHAR(50) NOT NULL, CHANGE mentor_feedback mentor_feedback LONGTEXT DEFAULT NULL, CHANGE entrepreneur_feedback entrepreneur_feedback LONGTEXT DEFAULT NULL, CHANGE meeting_link meeting_link VARCHAR(500) DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL;
DROP INDEX fk_session_request ON mentorship_session;
CREATE INDEX IDX_C48E665111D9B70F ON mentorship_session (mentorship_request_id);
ALTER TABLE mentorship_session ADD CONSTRAINT `fk_session_request` FOREIGN KEY (mentorship_request_id) REFERENCES mentorship_request (id) ON DELETE CASCADE;
ALTER TABLE posts DROP FOREIGN KEY `posts_ibfk_1`;
ALTER TABLE posts DROP FOREIGN KEY `posts_ibfk_1`;
ALTER TABLE posts CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX user_id ON posts;
CREATE INDEX IDX_885DBAFAA76ED395 ON posts (user_id);
ALTER TABLE posts ADD CONSTRAINT `posts_ibfk_1` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE post_reactions DROP FOREIGN KEY `post_reactions_ibfk_1`;
ALTER TABLE post_reactions DROP FOREIGN KEY `post_reactions_ibfk_2`;
ALTER TABLE post_reactions CHANGE reaction_type reaction_type ENUM('LIKE','LOVE','HAHA','WOW','SAD','ANGRY') NOT NULL DEFAULT 'LIKE';
DROP INDEX user_id ON post_reactions;
CREATE INDEX IDX_991D0144A76ED395 ON post_reactions (user_id);
DROP INDEX post_id ON post_reactions;
CREATE UNIQUE INDEX unique_reaction ON post_reactions (post_id, user_id);
ALTER TABLE post_reactions ADD CONSTRAINT `post_reactions_ibfk_1` FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE post_reactions ADD CONSTRAINT `post_reactions_ibfk_2` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX idx_etat ON progression;
ALTER TABLE progression DROP FOREIGN KEY `fk_progression_cours`;
ALTER TABLE progression DROP FOREIGN KEY `fk_progression_user`;
ALTER TABLE progression CHANGE pourcentage pourcentage NUMERIC(5, 2) NOT NULL, CHANGE points_xp points_xp INT NOT NULL, CHANGE niveau niveau INT NOT NULL, CHANGE etat etat ENUM('NON_COMMENCE','EN_COURS','COMPLETE','CERTIFIE') DEFAULT 'NON_COMMENCE', CHANGE date_debut date_debut DATETIME NOT NULL, CHANGE date_obtention date_obtention DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME NOT NULL;
DROP INDEX idx_user_progression ON progression;
CREATE INDEX IDX_D5B25073A76ED395 ON progression (user_id);
DROP INDEX idx_cours_progression ON progression;
CREATE INDEX IDX_D5B250737ECF78B0 ON progression (cours_id);
ALTER TABLE progression ADD CONSTRAINT `fk_progression_cours` FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE;
ALTER TABLE progression ADD CONSTRAINT `fk_progression_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE projet DROP FOREIGN KEY `FK_50159CA9A76ED395`;
ALTER TABLE projet CHANGE description description LONGTEXT DEFAULT NULL, CHANGE statut_projet statut_projet VARCHAR(20) DEFAULT NULL, CHANGE score_global score_global DOUBLE PRECISION DEFAULT NULL, CHANGE diagnostic_ia diagnostic_ia LONGTEXT DEFAULT NULL;
DROP INDEX fk_50159ca9a76ed395 ON projet;
CREATE INDEX IDX_50159CA9A76ED395 ON projet (user_id);
ALTER TABLE projet ADD CONSTRAINT `FK_50159CA9A76ED395` FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE threads DROP FOREIGN KEY `threads_ibfk_1`;
ALTER TABLE threads DROP FOREIGN KEY `threads_ibfk_2`;
ALTER TABLE threads DROP FOREIGN KEY `threads_ibfk_1`;
ALTER TABLE threads DROP FOREIGN KEY `threads_ibfk_2`;
ALTER TABLE threads CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL;
ALTER TABLE threads ADD CONSTRAINT FK_6F8E3DDDFE54D947 FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE;
ALTER TABLE threads ADD CONSTRAINT FK_6F8E3DDDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
DROP INDEX group_id ON threads;
CREATE INDEX IDX_6F8E3DDDFE54D947 ON threads (group_id);
DROP INDEX user_id ON threads;
CREATE INDEX IDX_6F8E3DDDA76ED395 ON threads (user_id);
ALTER TABLE threads ADD CONSTRAINT `threads_ibfk_1` FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE threads ADD CONSTRAINT `threads_ibfk_2` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE user DROP google_id, CHANGE role role ENUM('ADMIN','ENTREPRENEUR','MENTOR','INVESTISSEUR') NOT NULL DEFAULT 'ENTREPRENEUR', CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE verified verified TINYINT NOT NULL, CHANGE is_active is_active TINYINT NOT NULL, CHANGE is_banned is_banned TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE phone_verified phone_verified TINYINT NOT NULL, CHANGE login_attempts login_attempts SMALLINT DEFAULT 0 NOT NULL, CHANGE face_registered face_registered TINYINT NOT NULL, CHANGE total_xp total_xp INT NOT NULL;
DROP INDEX email ON user;
CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email);
ALTER TABLE user_connection DROP FOREIGN KEY `user_connection_ibfk_1`;
ALTER TABLE user_connection DROP FOREIGN KEY `user_connection_ibfk_2`;
ALTER TABLE user_connection CHANGE created_at created_at DATETIME NOT NULL;
DROP INDEX followed_id ON user_connection;
CREATE INDEX IDX_8E90B58AD956F010 ON user_connection (followed_id);
DROP INDEX follower_id ON user_connection;
CREATE UNIQUE INDEX unique_follow ON user_connection (follower_id, followed_id);
ALTER TABLE user_connection ADD CONSTRAINT `user_connection_ibfk_1` FOREIGN KEY (follower_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE user_connection ADD CONSTRAINT `user_connection_ibfk_2` FOREIGN KEY (followed_id) REFERENCES user (id) ON DELETE CASCADE;
