<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405140922 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE badge CHANGE rarete rarete ENUM(\'COMMUN\',\'RARE\',\'EPIQUE\',\'LEGENDAIRE\') DEFAULT \'COMMUN\'');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY `fk_appr_comment_cours`');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY `fk_appr_comment_user`');
        $this->addSql('DROP INDEX idx_appr_comment_cours ON comment');
        $this->addSql('CREATE INDEX IDX_9474526C7ECF78B0 ON comment (cours_id)');
        $this->addSql('DROP INDEX idx_appr_comment_user ON comment');
        $this->addSql('CREATE INDEX IDX_9474526CA76ED395 ON comment (user_id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT `fk_appr_comment_cours` FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT `fk_appr_comment_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY `fk_comment_thread`');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY `fk_comment_user`');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY `fk_comment_thread`');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY `fk_comment_user`');
        $this->addSql('ALTER TABLE comments CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AE2904019 FOREIGN KEY (thread_id) REFERENCES threads (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_comment_thread ON comments');
        $this->addSql('CREATE INDEX IDX_5F9E962AE2904019 ON comments (thread_id)');
        $this->addSql('DROP INDEX idx_comment_user ON comments');
        $this->addSql('CREATE INDEX IDX_5F9E962AA76ED395 ON comments (user_id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT `fk_comment_thread` FOREIGN KEY (thread_id) REFERENCES threads (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT `fk_comment_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_cours_niveau ON cours');
        $this->addSql('DROP INDEX idx_cours_type ON cours');
        $this->addSql('DROP INDEX idx_cours_certification ON cours');
        $this->addSql('ALTER TABLE cours ADD categorie VARCHAR(100) NOT NULL, ADD niveau_difficulte ENUM(\'DEBUTANT\',\'INTERMEDIAIRE\',\'AVANCE\',\'EXPERT\') NOT NULL DEFAULT \'DEBUTANT\', ADD actif TINYINT NOT NULL, DROP type, DROP niveau, DROP duree_minutes, CHANGE titre titre VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE certification certification TINYINT NOT NULL, CHANGE points_xp points_xp INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE createur_id duree_estimee INT DEFAULT NULL');
        $this->addSql('ALTER TABLE donnees_business DROP INDEX projet_id, ADD UNIQUE INDEX UNIQ_E8382063C18272 (projet_id)');
        $this->addSql('ALTER TABLE donnees_business CHANGE couts_estimes couts_estimes DOUBLE PRECISION DEFAULT NULL, CHANGE revenus_attendus revenus_attendus DOUBLE PRECISION DEFAULT NULL, CHANGE force_equipe force_equipe INT DEFAULT NULL, CHANGE marge_estimee marge_estimee DOUBLE PRECISION DEFAULT NULL, CHANGE ratio_rentabilite ratio_rentabilite DOUBLE PRECISION DEFAULT NULL, CHANGE score_financier score_financier DOUBLE PRECISION DEFAULT NULL, CHANGE score_marche score_marche DOUBLE PRECISION DEFAULT NULL, CHANGE score_equipe_calcule score_equipe_calcule DOUBLE PRECISION DEFAULT NULL, CHANGE score_risque_calcule score_risque_calcule DOUBLE PRECISION DEFAULT NULL, CHANGE raw_couts raw_couts LONGTEXT DEFAULT NULL, CHANGE raw_revenus raw_revenus LONGTEXT DEFAULT NULL, CHANGE raw_force_equipe raw_force_equipe LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event_participants DROP FOREIGN KEY `fk_ep_event`');
        $this->addSql('ALTER TABLE event_participants DROP FOREIGN KEY `fk_ep_user`');
        $this->addSql('ALTER TABLE event_participants DROP FOREIGN KEY `fk_ep_user`');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT FK_9C7A7A6171F7E88B FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT FK_9C7A7A61A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_ep_user ON event_participants');
        $this->addSql('CREATE INDEX IDX_9C7A7A61A76ED395 ON event_participants (user_id)');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT `fk_ep_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY `fk_event_creator`');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY `fk_event_creator`');
        $this->addSql('ALTER TABLE events CHANGE description description LONGTEXT DEFAULT NULL, CHANGE capacity capacity INT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574ADE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_event_creator ON events');
        $this->addSql('CREATE INDEX IDX_5387574ADE12AB56 ON events (created_by)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT `fk_event_creator` FOREIGN KEY (created_by) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_members DROP FOREIGN KEY `fk_gm_group`');
        $this->addSql('ALTER TABLE group_members DROP FOREIGN KEY `fk_gm_user`');
        $this->addSql('ALTER TABLE group_members DROP FOREIGN KEY `fk_gm_user`');
        $this->addSql('ALTER TABLE group_members CHANGE joined_at joined_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3FE54D947 FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_member_user ON group_members');
        $this->addSql('CREATE INDEX IDX_C3A086F3A76ED395 ON group_members (user_id)');
        $this->addSql('ALTER TABLE group_members ADD CONSTRAINT `fk_gm_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groups DROP FOREIGN KEY `fk_groups_admin`');
        $this->addSql('ALTER TABLE groups DROP FOREIGN KEY `fk_groups_admin`');
        $this->addSql('ALTER TABLE groups CHANGE description description LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE is_private is_private TINYINT NOT NULL');
        $this->addSql('ALTER TABLE groups ADD CONSTRAINT FK_F06D39706D1BCE6F FOREIGN KEY (group_admin_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_group_admin ON groups');
        $this->addSql('CREATE INDEX IDX_F06D39706D1BCE6F ON groups (group_admin_id)');
        $this->addSql('ALTER TABLE groups ADD CONSTRAINT `fk_groups_admin` FOREIGN KEY (group_admin_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_investor`');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_opportunity`');
        $this->addSql('DROP INDEX idx_offer_status ON investment_offer');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_investor`');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY `fk_offer_opportunity`');
        $this->addSql('ALTER TABLE investment_offer CHANGE status status ENUM(\'PENDING\',\'ACCEPTED\',\'REJECTED\') DEFAULT \'PENDING\', CHANGE paid paid TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT FK_4615B1CA9AE528DA FOREIGN KEY (investor_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT FK_4615B1CA9A34590F FOREIGN KEY (opportunity_id) REFERENCES investment_opportunity (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_offer_investor ON investment_offer');
        $this->addSql('CREATE INDEX IDX_4615B1CA9AE528DA ON investment_offer (investor_id)');
        $this->addSql('DROP INDEX idx_offer_opportunity ON investment_offer');
        $this->addSql('CREATE INDEX IDX_4615B1CA9A34590F ON investment_offer (opportunity_id)');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT `fk_offer_investor` FOREIGN KEY (investor_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT `fk_offer_opportunity` FOREIGN KEY (opportunity_id) REFERENCES investment_opportunity (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_opportunity DROP FOREIGN KEY `fk_opportunity_project`');
        $this->addSql('DROP INDEX idx_opportunity_status ON investment_opportunity');
        $this->addSql('DROP INDEX idx_opportunity_deadline ON investment_opportunity');
        $this->addSql('ALTER TABLE investment_opportunity DROP FOREIGN KEY `fk_opportunity_project`');
        $this->addSql('ALTER TABLE investment_opportunity CHANGE description description LONGTEXT DEFAULT NULL, CHANGE status status ENUM(\'OPEN\',\'CLOSED\',\'FUNDED\') DEFAULT \'OPEN\', CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE investment_opportunity ADD CONSTRAINT FK_498180B166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_opportunity_project ON investment_opportunity');
        $this->addSql('CREATE INDEX IDX_498180B166D1F9C ON investment_opportunity (project_id)');
        $this->addSql('ALTER TABLE investment_opportunity ADD CONSTRAINT `fk_opportunity_project` FOREIGN KEY (project_id) REFERENCES projet (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mentor_availability DROP FOREIGN KEY `fk_ma_mentor`');
        $this->addSql('ALTER TABLE mentor_availability CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_ma_mentor ON mentor_availability');
        $this->addSql('CREATE INDEX IDX_CB274DDFDB403044 ON mentor_availability (mentor_id)');
        $this->addSql('ALTER TABLE mentor_availability ADD CONSTRAINT `fk_ma_mentor` FOREIGN KEY (mentor_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mentorship_request CHANGE motivation motivation LONGTEXT DEFAULT NULL, CHANGE goals goals LONGTEXT DEFAULT NULL, CHANGE match_score match_score DOUBLE PRECISION DEFAULT NULL, CHANGE auto_approved auto_approved TINYINT NOT NULL, CHANGE status status VARCHAR(50) NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1A283063EA FOREIGN KEY (entrepreneur_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1ADB403044 FOREIGN KEY (mentor_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1A166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id)');
        $this->addSql('DROP INDEX idx_mr_entrepreneur ON mentorship_request');
        $this->addSql('CREATE INDEX IDX_2F5D3C1A283063EA ON mentorship_request (entrepreneur_id)');
        $this->addSql('DROP INDEX idx_mr_mentor ON mentorship_request');
        $this->addSql('CREATE INDEX IDX_2F5D3C1ADB403044 ON mentorship_request (mentor_id)');
        $this->addSql('DROP INDEX idx_mr_project ON mentorship_request');
        $this->addSql('CREATE INDEX IDX_2F5D3C1A166D1F9C ON mentorship_request (project_id)');
        $this->addSql('ALTER TABLE mentorship_session DROP FOREIGN KEY `fk_ms_request`');
        $this->addSql('ALTER TABLE mentorship_session CHANGE status status VARCHAR(50) NOT NULL, CHANGE mentor_feedback mentor_feedback LONGTEXT DEFAULT NULL, CHANGE entrepreneur_feedback entrepreneur_feedback LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX idx_ms_request ON mentorship_session');
        $this->addSql('CREATE INDEX IDX_C48E665111D9B70F ON mentorship_session (mentorship_request_id)');
        $this->addSql('ALTER TABLE mentorship_session ADD CONSTRAINT `fk_ms_request` FOREIGN KEY (mentorship_request_id) REFERENCES mentorship_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_reactions DROP FOREIGN KEY `fk_reaction_user`');
        $this->addSql('ALTER TABLE post_reactions CHANGE reaction_type reaction_type ENUM(\'LIKE\',\'LOVE\',\'HAHA\',\'WOW\',\'SAD\',\'ANGRY\') NOT NULL DEFAULT \'LIKE\'');
        $this->addSql('DROP INDEX idx_reaction_user ON post_reactions');
        $this->addSql('CREATE INDEX IDX_991D0144A76ED395 ON post_reactions (user_id)');
        $this->addSql('ALTER TABLE post_reactions ADD CONSTRAINT `fk_reaction_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE posts DROP FOREIGN KEY `fk_post_user`');
        $this->addSql('ALTER TABLE posts DROP FOREIGN KEY `fk_post_user`');
        $this->addSql('ALTER TABLE posts CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_post_user ON posts');
        $this->addSql('CREATE INDEX IDX_885DBAFAA76ED395 ON posts (user_id)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT `fk_post_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE progression DROP FOREIGN KEY `fk_progression_cours`');
        $this->addSql('DROP INDEX idx_progression_etat ON progression');
        $this->addSql('ALTER TABLE progression DROP FOREIGN KEY `fk_progression_cours`');
        $this->addSql('ALTER TABLE progression CHANGE pourcentage pourcentage NUMERIC(5, 2) NOT NULL, CHANGE points_xp points_xp INT NOT NULL, CHANGE niveau niveau INT NOT NULL, CHANGE etat etat ENUM(\'NON_COMMENCE\',\'EN_COURS\',\'COMPLETE\',\'CERTIFIE\') DEFAULT \'NON_COMMENCE\', CHANGE date_debut date_debut DATETIME NOT NULL, CHANGE date_obtention date_obtention DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B25073A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B250737ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_progression_user ON progression');
        $this->addSql('CREATE INDEX IDX_D5B25073A76ED395 ON progression (user_id)');
        $this->addSql('DROP INDEX idx_progression_cours ON progression');
        $this->addSql('CREATE INDEX IDX_D5B250737ECF78B0 ON progression (cours_id)');
        $this->addSql('DROP INDEX uk_user_cours ON progression');
        $this->addSql('CREATE UNIQUE INDEX unique_user_cours ON progression (user_id, cours_id)');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT `fk_progression_cours` FOREIGN KEY (cours_id) REFERENCES cours (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_projet_entrepreneur ON projet');
        $this->addSql('ALTER TABLE projet CHANGE description description LONGTEXT DEFAULT NULL, CHANGE statut_projet statut_projet VARCHAR(20) DEFAULT NULL, CHANGE score_global score_global DOUBLE PRECISION DEFAULT NULL, CHANGE diagnostic_ia diagnostic_ia LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('CREATE INDEX IDX_50159CA9A76ED395 ON projet (user_id)');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY `fk_thread_group`');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY `fk_thread_user`');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY `fk_thread_group`');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY `fk_thread_user`');
        $this->addSql('ALTER TABLE threads CHANGE content content LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT FK_6F8E3DDDFE54D947 FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT FK_6F8E3DDDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_thread_group ON threads');
        $this->addSql('CREATE INDEX IDX_6F8E3DDDFE54D947 ON threads (group_id)');
        $this->addSql('DROP INDEX idx_thread_user ON threads');
        $this->addSql('CREATE INDEX IDX_6F8E3DDDA76ED395 ON threads (user_id)');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT `fk_thread_group` FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT `fk_thread_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user DROP preferred_currency, DROP preferred_theme, DROP preferred_language, CHANGE role role ENUM(\'ADMIN\',\'ENTREPRENEUR\',\'MENTOR\',\'INVESTISSEUR\') NOT NULL DEFAULT \'ENTREPRENEUR\', CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE verified verified TINYINT NOT NULL, CHANGE phone_verified phone_verified TINYINT NOT NULL, CHANGE is_active is_active TINYINT NOT NULL, CHANGE is_banned is_banned TINYINT NOT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL, CHANGE face_registered face_registered TINYINT NOT NULL, CHANGE total_xp total_xp INT NOT NULL');
        $this->addSql('DROP INDEX email ON user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email)');
        $this->addSql('ALTER TABLE user_connection DROP FOREIGN KEY `user_connection_ibfk_2`');
        $this->addSql('ALTER TABLE user_connection CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('DROP INDEX followed_id ON user_connection');
        $this->addSql('CREATE INDEX IDX_8E90B58AD956F010 ON user_connection (followed_id)');
        $this->addSql('ALTER TABLE user_connection ADD CONSTRAINT `user_connection_ibfk_2` FOREIGN KEY (followed_id) REFERENCES user (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE badge CHANGE rarete rarete ENUM(\'COMMUN\', \'RARE\', \'EPIQUE\', \'LEGENDAIRE\') DEFAULT \'COMMUN\'');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526C7ECF78B0');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CA76ED395');
        $this->addSql('DROP INDEX idx_9474526c7ecf78b0 ON comment');
        $this->addSql('CREATE INDEX idx_appr_comment_cours ON comment (cours_id)');
        $this->addSql('DROP INDEX idx_9474526ca76ed395 ON comment');
        $this->addSql('CREATE INDEX idx_appr_comment_user ON comment (user_id)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C7ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962AE2904019');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962AA76ED395');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962AE2904019');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962AA76ED395');
        $this->addSql('ALTER TABLE comments CHANGE content content TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT `fk_comment_thread` FOREIGN KEY (thread_id) REFERENCES threads (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT `fk_comment_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_5f9e962ae2904019 ON comments');
        $this->addSql('CREATE INDEX idx_comment_thread ON comments (thread_id)');
        $this->addSql('DROP INDEX idx_5f9e962aa76ed395 ON comments');
        $this->addSql('CREATE INDEX idx_comment_user ON comments (user_id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AE2904019 FOREIGN KEY (thread_id) REFERENCES threads (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cours ADD type ENUM(\'VIDEO\', \'TEXTE\', \'QUIZ\', \'MIXTE\') DEFAULT \'TEXTE\' NOT NULL, ADD niveau ENUM(\'DEBUTANT\', \'INTERMEDIAIRE\', \'AVANCE\', \'EXPERT\') DEFAULT \'DEBUTANT\' NOT NULL, ADD duree_minutes INT DEFAULT 30, DROP categorie, DROP niveau_difficulte, DROP actif, CHANGE titre titre VARCHAR(200) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE points_xp points_xp INT DEFAULT 100 NOT NULL, CHANGE certification certification TINYINT DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE duree_estimee createur_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_cours_niveau ON cours (niveau)');
        $this->addSql('CREATE INDEX idx_cours_type ON cours (type)');
        $this->addSql('CREATE INDEX idx_cours_certification ON cours (certification)');
        $this->addSql('ALTER TABLE donnees_business DROP INDEX UNIQ_E8382063C18272, ADD INDEX projet_id (projet_id)');
        $this->addSql('ALTER TABLE donnees_business CHANGE couts_estimes couts_estimes DOUBLE PRECISION DEFAULT \'0\', CHANGE revenus_attendus revenus_attendus DOUBLE PRECISION DEFAULT \'0\', CHANGE force_equipe force_equipe INT DEFAULT 0, CHANGE marge_estimee marge_estimee DOUBLE PRECISION DEFAULT \'0\', CHANGE ratio_rentabilite ratio_rentabilite DOUBLE PRECISION DEFAULT \'0\', CHANGE score_financier score_financier DOUBLE PRECISION DEFAULT \'0\', CHANGE score_marche score_marche DOUBLE PRECISION DEFAULT \'0\', CHANGE score_equipe_calcule score_equipe_calcule DOUBLE PRECISION DEFAULT \'0\', CHANGE score_risque_calcule score_risque_calcule DOUBLE PRECISION DEFAULT \'0\', CHANGE raw_couts raw_couts TEXT DEFAULT NULL, CHANGE raw_revenus raw_revenus TEXT DEFAULT NULL, CHANGE raw_force_equipe raw_force_equipe TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574ADE12AB56');
        $this->addSql('ALTER TABLE events DROP FOREIGN KEY FK_5387574ADE12AB56');
        $this->addSql('ALTER TABLE events CHANGE description description TEXT DEFAULT NULL, CHANGE capacity capacity INT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT `fk_event_creator` FOREIGN KEY (created_by) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_5387574ade12ab56 ON events');
        $this->addSql('CREATE INDEX idx_event_creator ON events (created_by)');
        $this->addSql('ALTER TABLE events ADD CONSTRAINT FK_5387574ADE12AB56 FOREIGN KEY (created_by) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_participants DROP FOREIGN KEY FK_9C7A7A6171F7E88B');
        $this->addSql('ALTER TABLE event_participants DROP FOREIGN KEY FK_9C7A7A61A76ED395');
        $this->addSql('ALTER TABLE event_participants DROP FOREIGN KEY FK_9C7A7A61A76ED395');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT `fk_ep_event` FOREIGN KEY (event_id) REFERENCES events (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT `fk_ep_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_9c7a7a61a76ed395 ON event_participants');
        $this->addSql('CREATE INDEX idx_ep_user ON event_participants (user_id)');
        $this->addSql('ALTER TABLE event_participants ADD CONSTRAINT FK_9C7A7A61A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `groups` DROP FOREIGN KEY FK_F06D39706D1BCE6F');
        $this->addSql('ALTER TABLE `groups` DROP FOREIGN KEY FK_F06D39706D1BCE6F');
        $this->addSql('ALTER TABLE `groups` CHANGE description description TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE is_private is_private TINYINT DEFAULT 0');
        $this->addSql('ALTER TABLE `groups` ADD CONSTRAINT `fk_groups_admin` FOREIGN KEY (group_admin_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_f06d39706d1bce6f ON `groups`');
        $this->addSql('CREATE INDEX idx_group_admin ON `groups` (group_admin_id)');
        $this->addSql('ALTER TABLE `groups` ADD CONSTRAINT FK_F06D39706D1BCE6F FOREIGN KEY (group_admin_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_members DROP FOREIGN KEY FK_C3A086F3FE54D947');
        $this->addSql('ALTER TABLE group_members DROP FOREIGN KEY FK_C3A086F3A76ED395');
        $this->addSql('ALTER TABLE group_members DROP FOREIGN KEY FK_C3A086F3A76ED395');
        $this->addSql('ALTER TABLE group_members CHANGE joined_at joined_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE group_members ADD CONSTRAINT `fk_gm_group` FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_members ADD CONSTRAINT `fk_gm_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_c3a086f3a76ed395 ON group_members');
        $this->addSql('CREATE INDEX idx_member_user ON group_members (user_id)');
        $this->addSql('ALTER TABLE group_members ADD CONSTRAINT FK_C3A086F3A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY FK_4615B1CA9AE528DA');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY FK_4615B1CA9A34590F');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY FK_4615B1CA9AE528DA');
        $this->addSql('ALTER TABLE investment_offer DROP FOREIGN KEY FK_4615B1CA9A34590F');
        $this->addSql('ALTER TABLE investment_offer CHANGE status status ENUM(\'PENDING\', \'ACCEPTED\', \'REJECTED\') DEFAULT \'PENDING\', CHANGE paid paid TINYINT DEFAULT 0, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT `fk_offer_investor` FOREIGN KEY (investor_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT `fk_offer_opportunity` FOREIGN KEY (opportunity_id) REFERENCES investment_opportunity (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_offer_status ON investment_offer (status)');
        $this->addSql('DROP INDEX idx_4615b1ca9a34590f ON investment_offer');
        $this->addSql('CREATE INDEX idx_offer_opportunity ON investment_offer (opportunity_id)');
        $this->addSql('DROP INDEX idx_4615b1ca9ae528da ON investment_offer');
        $this->addSql('CREATE INDEX idx_offer_investor ON investment_offer (investor_id)');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT FK_4615B1CA9AE528DA FOREIGN KEY (investor_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_offer ADD CONSTRAINT FK_4615B1CA9A34590F FOREIGN KEY (opportunity_id) REFERENCES investment_opportunity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE investment_opportunity DROP FOREIGN KEY FK_498180B166D1F9C');
        $this->addSql('ALTER TABLE investment_opportunity DROP FOREIGN KEY FK_498180B166D1F9C');
        $this->addSql('ALTER TABLE investment_opportunity CHANGE description description TEXT DEFAULT NULL, CHANGE status status ENUM(\'OPEN\', \'CLOSED\', \'FUNDED\') DEFAULT \'OPEN\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE investment_opportunity ADD CONSTRAINT `fk_opportunity_project` FOREIGN KEY (project_id) REFERENCES projet (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_opportunity_status ON investment_opportunity (status)');
        $this->addSql('CREATE INDEX idx_opportunity_deadline ON investment_opportunity (deadline)');
        $this->addSql('DROP INDEX idx_498180b166d1f9c ON investment_opportunity');
        $this->addSql('CREATE INDEX idx_opportunity_project ON investment_opportunity (project_id)');
        $this->addSql('ALTER TABLE investment_opportunity ADD CONSTRAINT FK_498180B166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mentorship_request DROP FOREIGN KEY FK_2F5D3C1A283063EA');
        $this->addSql('ALTER TABLE mentorship_request DROP FOREIGN KEY FK_2F5D3C1ADB403044');
        $this->addSql('ALTER TABLE mentorship_request DROP FOREIGN KEY FK_2F5D3C1A166D1F9C');
        $this->addSql('ALTER TABLE mentorship_request DROP FOREIGN KEY FK_2F5D3C1A283063EA');
        $this->addSql('ALTER TABLE mentorship_request DROP FOREIGN KEY FK_2F5D3C1ADB403044');
        $this->addSql('ALTER TABLE mentorship_request DROP FOREIGN KEY FK_2F5D3C1A166D1F9C');
        $this->addSql('ALTER TABLE mentorship_request CHANGE motivation motivation TEXT DEFAULT NULL, CHANGE goals goals TEXT DEFAULT NULL, CHANGE match_score match_score FLOAT DEFAULT NULL, CHANGE auto_approved auto_approved TINYINT DEFAULT 0, CHANGE status status VARCHAR(50) DEFAULT \'PENDING\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_2f5d3c1a166d1f9c ON mentorship_request');
        $this->addSql('CREATE INDEX idx_mr_project ON mentorship_request (project_id)');
        $this->addSql('DROP INDEX idx_2f5d3c1a283063ea ON mentorship_request');
        $this->addSql('CREATE INDEX idx_mr_entrepreneur ON mentorship_request (entrepreneur_id)');
        $this->addSql('DROP INDEX idx_2f5d3c1adb403044 ON mentorship_request');
        $this->addSql('CREATE INDEX idx_mr_mentor ON mentorship_request (mentor_id)');
        $this->addSql('ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1A283063EA FOREIGN KEY (entrepreneur_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1ADB403044 FOREIGN KEY (mentor_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE mentorship_request ADD CONSTRAINT FK_2F5D3C1A166D1F9C FOREIGN KEY (project_id) REFERENCES projet (id)');
        $this->addSql('ALTER TABLE mentorship_session DROP FOREIGN KEY FK_C48E665111D9B70F');
        $this->addSql('ALTER TABLE mentorship_session CHANGE status status VARCHAR(50) DEFAULT \'SCHEDULED\', CHANGE mentor_feedback mentor_feedback TEXT DEFAULT NULL, CHANGE entrepreneur_feedback entrepreneur_feedback TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_c48e665111d9b70f ON mentorship_session');
        $this->addSql('CREATE INDEX idx_ms_request ON mentorship_session (mentorship_request_id)');
        $this->addSql('ALTER TABLE mentorship_session ADD CONSTRAINT FK_C48E665111D9B70F FOREIGN KEY (mentorship_request_id) REFERENCES mentorship_request (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mentor_availability DROP FOREIGN KEY FK_CB274DDFDB403044');
        $this->addSql('ALTER TABLE mentor_availability CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_cb274ddfdb403044 ON mentor_availability');
        $this->addSql('CREATE INDEX idx_ma_mentor ON mentor_availability (mentor_id)');
        $this->addSql('ALTER TABLE mentor_availability ADD CONSTRAINT FK_CB274DDFDB403044 FOREIGN KEY (mentor_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE posts DROP FOREIGN KEY FK_885DBAFAA76ED395');
        $this->addSql('ALTER TABLE posts DROP FOREIGN KEY FK_885DBAFAA76ED395');
        $this->addSql('ALTER TABLE posts CHANGE content content TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT `fk_post_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_885dbafaa76ed395 ON posts');
        $this->addSql('CREATE INDEX idx_post_user ON posts (user_id)');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT FK_885DBAFAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_reactions DROP FOREIGN KEY FK_991D0144A76ED395');
        $this->addSql('ALTER TABLE post_reactions CHANGE reaction_type reaction_type ENUM(\'LIKE\', \'LOVE\', \'HAHA\', \'WOW\', \'SAD\', \'ANGRY\') DEFAULT \'LIKE\' NOT NULL');
        $this->addSql('DROP INDEX idx_991d0144a76ed395 ON post_reactions');
        $this->addSql('CREATE INDEX idx_reaction_user ON post_reactions (user_id)');
        $this->addSql('ALTER TABLE post_reactions ADD CONSTRAINT FK_991D0144A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE progression DROP FOREIGN KEY FK_D5B25073A76ED395');
        $this->addSql('ALTER TABLE progression DROP FOREIGN KEY FK_D5B250737ECF78B0');
        $this->addSql('ALTER TABLE progression DROP FOREIGN KEY FK_D5B25073A76ED395');
        $this->addSql('ALTER TABLE progression DROP FOREIGN KEY FK_D5B250737ECF78B0');
        $this->addSql('ALTER TABLE progression CHANGE pourcentage pourcentage NUMERIC(5, 2) DEFAULT \'0.00\' COMMENT \'Pourcentage de 0.00 ├á 100.00\', CHANGE points_xp points_xp INT DEFAULT 0, CHANGE niveau niveau INT DEFAULT 1, CHANGE etat etat ENUM(\'NON_COMMENCE\', \'EN_COURS\', \'COMPLETE\', \'CERTIFIE\') DEFAULT \'NON_COMMENCE\', CHANGE date_debut date_debut DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE date_obtention date_obtention DATETIME DEFAULT NULL COMMENT \'Date de compl├®tion du cours\', CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT `fk_progression_cours` FOREIGN KEY (cours_id) REFERENCES cours (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_progression_etat ON progression (etat)');
        $this->addSql('DROP INDEX idx_d5b250737ecf78b0 ON progression');
        $this->addSql('CREATE INDEX idx_progression_cours ON progression (cours_id)');
        $this->addSql('DROP INDEX unique_user_cours ON progression');
        $this->addSql('CREATE UNIQUE INDEX uk_user_cours ON progression (user_id, cours_id)');
        $this->addSql('DROP INDEX idx_d5b25073a76ed395 ON progression');
        $this->addSql('CREATE INDEX idx_progression_user ON progression (user_id)');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B25073A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B250737ECF78B0 FOREIGN KEY (cours_id) REFERENCES cours (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projet DROP FOREIGN KEY FK_50159CA9A76ED395');
        $this->addSql('DROP INDEX IDX_50159CA9A76ED395 ON projet');
        $this->addSql('ALTER TABLE projet CHANGE description description TEXT DEFAULT NULL, CHANGE statut_projet statut_projet VARCHAR(20) DEFAULT \'BROUILLON\', CHANGE score_global score_global DOUBLE PRECISION DEFAULT \'0\', CHANGE diagnostic_ia diagnostic_ia TEXT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_projet_entrepreneur ON projet (entrepreneur_id)');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY FK_6F8E3DDDFE54D947');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY FK_6F8E3DDDA76ED395');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY FK_6F8E3DDDFE54D947');
        $this->addSql('ALTER TABLE threads DROP FOREIGN KEY FK_6F8E3DDDA76ED395');
        $this->addSql('ALTER TABLE threads CHANGE content content TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT `fk_thread_group` FOREIGN KEY (group_id) REFERENCES groups (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT `fk_thread_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_6f8e3dddfe54d947 ON threads');
        $this->addSql('CREATE INDEX idx_thread_group ON threads (group_id)');
        $this->addSql('DROP INDEX idx_6f8e3ddda76ed395 ON threads');
        $this->addSql('CREATE INDEX idx_thread_user ON threads (user_id)');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT FK_6F8E3DDDFE54D947 FOREIGN KEY (group_id) REFERENCES `groups` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE threads ADD CONSTRAINT FK_6F8E3DDDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD preferred_currency VARCHAR(3) DEFAULT \'EUR\', ADD preferred_theme VARCHAR(10) DEFAULT \'light\', ADD preferred_language VARCHAR(5) DEFAULT \'fr\', CHANGE role role ENUM(\'ADMIN\', \'ENTREPRENEUR\', \'MENTOR\', \'INVESTISSEUR\') DEFAULT \'ENTREPRENEUR\' NOT NULL, CHANGE bio bio TEXT DEFAULT NULL, CHANGE verified verified TINYINT DEFAULT 0 NOT NULL, CHANGE phone_verified phone_verified TINYINT DEFAULT 0 NOT NULL, CHANGE is_active is_active TINYINT DEFAULT 1 NOT NULL, CHANGE is_banned is_banned TINYINT DEFAULT 0 NOT NULL, CHANGE face_registered face_registered TINYINT DEFAULT 0 NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE total_xp total_xp INT DEFAULT 0 NOT NULL');
        $this->addSql('DROP INDEX uniq_8d93d649e7927c74 ON user');
        $this->addSql('CREATE UNIQUE INDEX email ON user (email)');
        $this->addSql('ALTER TABLE user_connection DROP FOREIGN KEY FK_8E90B58AD956F010');
        $this->addSql('ALTER TABLE user_connection CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('DROP INDEX idx_8e90b58ad956f010 ON user_connection');
        $this->addSql('CREATE INDEX followed_id ON user_connection (followed_id)');
        $this->addSql('ALTER TABLE user_connection ADD CONSTRAINT FK_8E90B58AD956F010 FOREIGN KEY (followed_id) REFERENCES user (id) ON DELETE CASCADE');
    }
}
